#ifndef LIB_SELECTIONSORT_BINSEARCH_GLOBAL_H
#define LIB_SELECTIONSORT_BINSEARCH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIB_SELECTIONSORT_BINSEARCH_LIBRARY)
#define LIB_SELECTIONSORT_BINSEARCH_EXPORT Q_DECL_EXPORT
#else
#define LIB_SELECTIONSORT_BINSEARCH_EXPORT Q_DECL_IMPORT
#endif

#endif // LIB_SELECTIONSORT_BINSEARCH_GLOBAL_H
